minimum-gas-prices = "0.0025uosmo"
pruning = "custom"
pruning-keep-recent = "10000"
pruning-interval = "100"
halt-height = 0
halt-time = 0
min-retain-blocks = 0
inter-block-cache = true
index-events = []
iavl-cache-size = 781250
iavl-disable-fastnode = false
iavl-lazy-loading = false
app-db-backend = ""

[api]
  address = "tcp://0.0.0.0:1317"
  enable = true
  enabled-unsafe-cors = true
  max-open-connections = 1000
  rpc-max-body-bytes = 1000000
  rpc-read-timeout = 10
  rpc-write-timeout = 0
  swagger = true

[grpc]
  address = "0.0.0.0:9090"
  concurrency = false
  enable = true
  max-recv-msg-size = "10485760"
  max-send-msg-size = "2147483647"

[grpc-web]
  address = "0.0.0.0:9091"
  enable = true
  enable-unsafe-cors = true

[store]
  streamers = []

[streamers]
[streamers.file]
  keys = ['*']
  write_dir = ""
  prefix = ""
  output-metadata = "true"
  stop-node-on-error = "true"
  fsync = "false"

[mempool]
  max-txs = "500"

[osmosis-mempool]
  arbitrage-min-gas-fee = ".05"
  max-gas-wanted-per-tx = "15000000"
  min-gas-price-for-high-gas-tx = ".003"
  adaptive-fee-enabled = "true"

[rosetta]
  address = ":8080"
  blockchain = "app"
  enable = false
  network = "network"
  offline = false
  retries = 3
  enable-fee-suggestion = false
  gas-to-suggest = 200000
  denom-to-suggest = "uosmo"

[state-sync]
  snapshot-interval = "0"
  snapshot-keep-recent = 2

[telemetry]
  service-name = ""
  enabled = true
  enable-hostname = false
  enable-hostname-label = false
  enable-service-label = false
  prometheus-retention-time = 15
  global-labels = []

[osmosis-sqs]
  is-enabled = "true"
  grpc-ingest-address = "osmosis-sqs:50051"
  grpc-ingest-max-call-size-bytes = "61644800"

[otel]
  enabled = "true"
  service-name = "do-eu-ce-sqs-prod-0-osmosis"

[wasm]
  query_gas_limit = 3000000
  memory_cache_size = 1000